<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>Shared.Telemetry</AssemblyName>
		<RootNamespace>Shared.Telemetry</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="OpenTelemetry.Extensions.Hosting"/>
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol"/>
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore"/>
		<PackageReference Include="OpenTelemetry.Instrumentation.Http"/>
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime"/>
		<PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore"/>
	</ItemGroup>

</Project>