<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>Shared.Logging.Sql</AssemblyName>
		<RootNamespace>Shared.Logging.Sql</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient"/>
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions"/>
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
	</ItemGroup>

</Project>